using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Photon.Pun;
using Photon.Realtime;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using System.IO;
using System;
using System.Collections;
using UnityEngine;
using Photon.Pun.Demo.Cockpit;

public class MasterServer : MonoBehaviourPunCallbacks
{
    public FormU_online FO;
    private PhotonView photonView;
    public GameObject pir_w;
    public GameObject pir_b;
    public GameObject boat_w;
    public GameObject boat_b;
    public GameObject pir_y;
    public GameObject pir_r;
    public GameObject boat_y;
    public GameObject boat_r;
    public GameObject pir_w_1;
    public GameObject pir_w_2;
    public GameObject pir_w_3;
    public GameObject boat_w_1;
    public GameObject pir_b_1;
    public GameObject pir_b_2;
    public GameObject pir_b_3;
    public GameObject boat_b_1;
    public GameObject pir_y_1;
    public GameObject pir_y_2;
    public GameObject pir_y_3;
    public GameObject boat_y_1;
    public GameObject pir_r_1;
    public GameObject pir_r_2;
    public GameObject pir_r_3;
    public GameObject boat_r_1;
    public GameObject down_p;
    public GameObject down_1;
    public GameObject down_2;
    public GameObject down_3;
    public GameObject down_4;
    public GameObject down_5;
    public GameObject down_6;
    public GameObject down_7;
    public GameObject down_8;
    public GameObject down_9;
    public GameObject down_10;
    public GameObject down_11;
    public GameObject down_12;
    public GameObject down_13;
    public GameObject down_14;
    public GameObject down_15;
    public GameObject down_16;
    public GameObject down_17;
    public GameObject down_18;
    public GameObject down_19;
    public GameObject down_20;
    public GameObject down_21;
    public GameObject down_22;
    public GameObject down_23;
    public GameObject down_24;
    public GameObject down_25;
    public GameObject down_26;
    public GameObject down_27;
    public GameObject down_28;
    public GameObject down_29;
    public GameObject down_30;
    public GameObject down_31;
    public GameObject down_32;
    public GameObject down_33;
    public GameObject down_34;
    public GameObject down_35;
    public GameObject down_36;
    public GameObject down_37;
    public GameObject down_38;
    public GameObject down_39;
    public GameObject down_40;
    public GameObject down_41;
    public GameObject down_42;
    public GameObject down_43;
    public GameObject down_44;
    public GameObject down_45;
    public GameObject down_46;
    public GameObject down_47;
    public GameObject down_48;
    public GameObject down_49;
    public GameObject down_50;
    public GameObject down_51;
    public GameObject down_52;
    public GameObject down_53;
    public GameObject down_54;
    public GameObject down_55;
    public GameObject down_56;
    public GameObject down_57;
    public GameObject down_58;
    public GameObject down_59;
    public GameObject down_60;
    public GameObject down_61;
    public GameObject down_62;
    public GameObject down_63;
    public GameObject down_64;
    public GameObject down_65;
    public GameObject down_66;
    public GameObject down_67;
    public GameObject down_68;
    public GameObject down_69;
    public GameObject down_70;
    public GameObject down_71;
    public GameObject down_72;
    public GameObject down_73;
    public GameObject down_74;
    public GameObject down_75;
    public GameObject down_76;
    public GameObject down_77;
    public GameObject down_78;
    public GameObject down_79;
    public GameObject down_80;
    public GameObject down_81;
    public GameObject down_82;
    public GameObject down_83;
    public GameObject down_84;
    public GameObject down_85;
    public GameObject down_86;
    public GameObject down_87;
    public GameObject down_88;
    public GameObject down_89;
    public GameObject down_90;
    public GameObject down_91;
    public GameObject down_92;
    public GameObject down_93;
    public GameObject down_94;
    public GameObject down_95;
    public GameObject down_96;
    public GameObject down_97;
    public GameObject down_98;
    public GameObject down_99;
    public GameObject down_100;
    public GameObject down_101;
    public GameObject down_102;
    public GameObject down_103;
    public GameObject down_104;
    public GameObject down_105;
    public GameObject down_106;
    public GameObject down_107;
    public GameObject down_108;
    public GameObject down_109;
    public GameObject down_110;
    public GameObject down_111;
    public GameObject down_112;
    public GameObject down_113;
    public GameObject down_114;
    public GameObject down_115;
    public GameObject down_116;
    public GameObject down_117;
    public GameObject down_118;
    public GameObject down_119;
    public GameObject down_120;
    public GameObject down_121;
    public GameObject down_122;
    public GameObject down_123;
    public GameObject down_124;
    public GameObject down_125;
    public GameObject down_126;
    public GameObject down_127;
    public GameObject down_128;
    public GameObject down_129;
    public GameObject down_130;
    public GameObject down_131;
    public GameObject down_132;
    public GameObject down_133;
    public GameObject down_134;
    public GameObject down_135;
    public GameObject down_136;
    public GameObject down_137;
    public GameObject down_138;
    public GameObject down_139;
    public GameObject down_140;
    public GameObject down_141;
    public GameObject down_142;
    public GameObject down_143;
    public GameObject down_144;
    public GameObject down_145;
    public GameObject down_146;
    public GameObject down_147;
    public GameObject down_148;
    public GameObject down_149;
    public GameObject down_150;
    public GameObject down_151;
    public GameObject down_152;
    public GameObject down_153;
    public GameObject down_154;
    public GameObject down_155;
    public GameObject down_156;
    public GameObject down_157;
    public GameObject down_158;
    public GameObject down_159;
    public GameObject down_160;
    public GameObject down_161;
    public GameObject down_162;
    public GameObject down_163;
    public GameObject down_164;
    public GameObject down_165;
    public GameObject down_166;
    public GameObject down_167;
    public GameObject down_168;
    public GameObject down_169;
    public GameObject down_170;
    public GameObject down_171;
    public GameObject down_172;
    public GameObject down_173;
    public GameObject down_174;
    public GameObject down_175;
    public GameObject down_176;
    public GameObject down_177;
    public GameObject down_178;
    public GameObject down_179;
    public GameObject down_180;
    public GameObject down_181;
    public GameObject down_182;
    public GameObject down_183;
    public GameObject down_184;
    public GameObject down_185;
    public GameObject down_186;
    public GameObject down_187;
    public GameObject down_188;
    public GameObject down_189;
    public GameObject down_190;
    public GameObject down_191;
    public GameObject down_192;
    public GameObject down_193;
    public GameObject down_194;
    public GameObject down_195;
    public GameObject down_196;
    public GameObject down_197;
    public GameObject down_198;
    public GameObject down_199;
    public GameObject down_200;
    public GameObject down_201;
    public GameObject down_202;
    public GameObject down_203;
    public GameObject down_204;
    public GameObject down_205;
    public GameObject down_206;
    public GameObject down_207;
    public GameObject down_208;
    public GameObject down_209;
    public GameObject down_210;
    public GameObject down_211;
    public GameObject down_212;
    public GameObject down_213;
    public GameObject down_214;
    public GameObject down_215;
    public GameObject down_216;
    public GameObject down_217;
    public GameObject down_218;
    public GameObject down_219;
    public GameObject down_220;
    public GameObject down_221;
    public GameObject down_222;
    public GameObject down_223;
    public GameObject down_224;
    public GameObject down_225;
    public GameObject light_1;
    public GameObject light_2;
    public GameObject light_3;
    public GameObject light_4;
    public GameObject light_5;
    public GameObject light_6;
    public GameObject light_7;
    public GameObject light_8;
    public GameObject light_9;
    public GameObject light_10;
    public GameObject light_11;
    public GameObject light_12;
    public GameObject light_13;
    public GameObject light_14;
    public GameObject light_15;
    public GameObject light_16;
    public GameObject light_17;
    public GameObject light_18;
    public GameObject light_19;
    public GameObject light_20;
    public GameObject light_21;
    public GameObject light_22;
    public GameObject light_23;
    public GameObject light_24;
    public GameObject light_25;
    public GameObject light_26;
    public GameObject light_27;
    public GameObject light_28;
    public GameObject light_29;
    public GameObject light_30;
    public GameObject light_31;
    public GameObject light_32;
    public GameObject light_33;
    public GameObject light_34;
    public GameObject light_35;
    public GameObject light_36;
    public GameObject light_37;
    public GameObject light_38;
    public GameObject light_39;
    public GameObject light_40;
    public GameObject light_41;
    public GameObject light_42;
    public GameObject light_43;
    public GameObject light_44;
    public GameObject light_45;
    public GameObject light_46;
    public GameObject light_47;
    public GameObject light_48;
    public GameObject light_49;
    public GameObject light_50;
    public GameObject light_51;
    public GameObject light_52;
    public GameObject light_53;
    public GameObject light_54;
    public GameObject light_55;
    public GameObject light_56;
    public GameObject light_57;
    public GameObject light_58;
    public GameObject light_59;
    public GameObject light_60;
    public GameObject light_61;
    public GameObject light_62;
    public GameObject light_63;
    public GameObject light_64;
    public GameObject light_65;
    public GameObject light_66;
    public GameObject light_67;
    public GameObject light_68;
    public GameObject light_69;
    public GameObject light_70;
    public GameObject light_71;
    public GameObject light_72;
    public GameObject light_73;
    public GameObject light_74;
    public GameObject light_75;
    public GameObject light_76;
    public GameObject light_77;
    public GameObject light_78;
    public GameObject light_79;
    public GameObject light_80;
    public GameObject light_81;
    public GameObject light_82;
    public GameObject light_83;
    public GameObject light_84;
    public GameObject light_85;
    public GameObject light_86;
    public GameObject light_87;
    public GameObject light_88;
    public GameObject light_89;
    public GameObject light_90;
    public GameObject light_91;
    public GameObject light_92;
    public GameObject light_93;
    public GameObject light_94;
    public GameObject light_95;
    public GameObject light_96;
    public GameObject light_97;
    public GameObject light_98;
    public GameObject light_99;
    public GameObject light_100;
    public GameObject light_101;
    public GameObject light_102;
    public GameObject light_103;
    public GameObject light_104;
    public GameObject light_105;
    public GameObject light_106;
    public GameObject light_107;
    public GameObject light_108;
    public GameObject light_109;
    public GameObject light_110;
    public GameObject light_111;
    public GameObject light_112;
    public GameObject light_113;
    public GameObject light_114;
    public GameObject light_115;
    public GameObject light_116;
    public GameObject light_117;
    public GameObject light_118;
    public GameObject light_119;
    public GameObject light_120;
    public GameObject light_121;
    public GameObject light_122;
    public GameObject light_123;
    public GameObject light_124;
    public GameObject light_125;
    public GameObject light_126;
    public GameObject light_127;
    public GameObject light_128;
    public GameObject light_129;
    public GameObject light_130;
    public GameObject light_131;
    public GameObject light_132;
    public GameObject light_133;
    public GameObject light_134;
    public GameObject light_135;
    public GameObject light_136;
    public GameObject light_137;
    public GameObject light_138;
    public GameObject light_139;
    public GameObject light_140;
    public GameObject light_141;
    public GameObject light_142;
    public GameObject light_143;
    public GameObject light_144;
    public GameObject light_145;
    public GameObject light_146;
    public GameObject light_147;
    public GameObject light_148;
    public GameObject light_149;
    public GameObject light_150;
    public GameObject light_151;
    public GameObject light_152;
    public GameObject light_153;
    public GameObject light_154;
    public GameObject light_155;
    public GameObject light_156;
    public GameObject light_157;
    public GameObject light_158;
    public GameObject light_159;
    public GameObject light_160;
    public GameObject light_161;
    public GameObject light_162;
    public GameObject light_163;
    public GameObject light_164;
    public GameObject light_165;
    public GameObject light_166;
    public GameObject light_167;
    public GameObject light_168;
    public GameObject light_169;
    public GameObject light_170;
    public GameObject light_171;
    public GameObject light_172;
    public GameObject light_173;
    public GameObject light_174;
    public GameObject light_175;
    public GameObject light_176;
    public GameObject light_177;
    public GameObject light_178;
    public GameObject light_179;
    public GameObject light_180;
    public GameObject light_181;
    public GameObject light_182;
    public GameObject light_183;
    public GameObject light_184;
    public GameObject light_185;
    public GameObject light_186;
    public GameObject light_187;
    public GameObject light_188;
    public GameObject light_189;
    public GameObject light_190;
    public GameObject light_191;
    public GameObject light_192;
    public GameObject light_193;
    public GameObject light_194;
    public GameObject light_195;
    public GameObject light_196;
    public GameObject light_197;
    public GameObject light_198;
    public GameObject light_199;
    public GameObject light_200;
    public GameObject light_201;
    public GameObject light_202;
    public GameObject light_203;
    public GameObject light_204;
    public GameObject light_205;
    public GameObject light_206;
    public GameObject light_207;
    public GameObject light_208;
    public GameObject light_209;
    public GameObject light_210;
    public GameObject light_211;
    public GameObject light_212;
    public GameObject light_213;
    public GameObject light_214;
    public GameObject light_215;
    public GameObject light_216;
    public GameObject light_217;
    public GameObject light_218;
    public GameObject light_219;
    public GameObject light_220;
    public GameObject light_221;
    public GameObject light_222;
    public GameObject light_223;
    public GameObject light_224;
    public GameObject light_225;
    public Material mat;
    public bool Exit = false;
    private const string roomName = "RoomName";
    private RoomInfo[] roomsList;
    private bool IsSpawning = false;
    private bool costumProp = false;
    public string NickName;
    public PUN pun;
    private string RoomName = " ";
    void Start()
    {
        photonView = GetComponent<PhotonView>();
        PhotonNetwork.AutomaticallySyncScene = true;
        PhotonNetwork.GameVersion = "1";
        PhotonNetwork.ConnectUsingSettings();
        NickName = PhotonNetwork.NickName;
    }
    public override void OnJoinedRoom()// когда подключились
    {
        FO.PoP();
        //FO.ToT();
        /*
        Debug.Log("OnJoinedRoom"+ NickName);
        if (PhotonNetwork.CurrentRoom.PlayerCount==1)
        {
            bool down = true;
            if (down)
            {
                down_1 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0f, 15f), Quaternion.identity);
                down_2 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0f, 15f), Quaternion.identity);
                down_3 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0f, 15f), Quaternion.identity);
                down_4 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0f, 15f), Quaternion.identity);
                down_5 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0f, 15f), Quaternion.identity);
                down_6 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0f, 15f), Quaternion.identity);
                down_7 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0f, 15f), Quaternion.identity);
                down_8 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0f, 15f), Quaternion.identity);
                down_9 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0f, 15f), Quaternion.identity);
                down_10 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0f, 15f), Quaternion.identity);
                down_11 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0f, 15f), Quaternion.identity);
                down_12 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0f, 15f), Quaternion.identity);
                down_13 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0f, 15f), Quaternion.identity);
                down_14 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0f, 15f), Quaternion.identity);
                down_15 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0f, 15f), Quaternion.identity);
                down_16 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0f, 5f), Quaternion.identity);
                down_17 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0f, 5f), Quaternion.identity);
                down_18 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0f, 5f), Quaternion.identity);
                down_19 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0f, 5f), Quaternion.identity);
                down_20 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0f, 5f), Quaternion.identity);
                down_21 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0f, 5f), Quaternion.identity);
                down_22 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0f, 5f), Quaternion.identity);
                down_23 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0f, 5f), Quaternion.identity);
                down_24 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0f, 5f), Quaternion.identity);
                down_25 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0f, 5f), Quaternion.identity);
                down_26 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0f, 5f), Quaternion.identity);
                down_27 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0f, 5f), Quaternion.identity);
                down_28 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0f, 5f), Quaternion.identity);
                down_29 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0f, 5f), Quaternion.identity);
                down_30 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0f, 5f), Quaternion.identity);
                down_31 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0f, -5f), Quaternion.identity);
                down_32 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0f, -5f), Quaternion.identity);
                down_33 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0f, -5f), Quaternion.identity);
                down_34 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0f, -5f), Quaternion.identity);
                down_35 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0f, -5f), Quaternion.identity);
                down_36 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0f, -5f), Quaternion.identity);
                down_37 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0f, -5f), Quaternion.identity);
                down_38 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0f, -5f), Quaternion.identity);
                down_39 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0f, -5f), Quaternion.identity);
                down_40 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0f, -5f), Quaternion.identity);
                down_41 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0f, -5f), Quaternion.identity);
                down_42 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0f, -5f), Quaternion.identity);
                down_43 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0f, -5f), Quaternion.identity);
                down_44 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0f, -5f), Quaternion.identity);
                down_45 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0f, -5f), Quaternion.identity);
                down_46 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0f, -15f), Quaternion.identity);
                down_47 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0f, -15f), Quaternion.identity);
                down_48 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0f, -15f), Quaternion.identity);
                down_49 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0f, -15f), Quaternion.identity);
                down_50 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0f, -15f), Quaternion.identity);
                down_51 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0f, -15f), Quaternion.identity);
                down_52 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0f, -15f), Quaternion.identity);
                down_53 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0f, -15f), Quaternion.identity);
                down_54 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0f, -15f), Quaternion.identity);
                down_55 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0f, -15f), Quaternion.identity);
                down_56 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0f, -15f), Quaternion.identity);
                down_57 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0f, -15f), Quaternion.identity);
                down_58 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0f, -15f), Quaternion.identity);
                down_59 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0f, -15f), Quaternion.identity);
                down_60 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0f, -15f), Quaternion.identity);
                down_61 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0f, -25f), Quaternion.identity);
                down_62 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0f, -25f), Quaternion.identity);
                down_63 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0f, -25f), Quaternion.identity);
                down_64 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0f, -25f), Quaternion.identity);
                down_65 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0f, -25f), Quaternion.identity);
                down_66 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0f, -25f), Quaternion.identity);
                down_67 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0f, -25f), Quaternion.identity);
                down_68 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0f, -25f), Quaternion.identity);
                down_69 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0f, -25f), Quaternion.identity);
                down_70 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0f, -25f), Quaternion.identity);
                down_71 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0f, -25f), Quaternion.identity);
                down_72 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0f, -25f), Quaternion.identity);
                down_73 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0f, -25f), Quaternion.identity);
                down_74 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0f, -25f), Quaternion.identity);
                down_75 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0f, -25f), Quaternion.identity);
                down_76 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0f, -35f), Quaternion.identity);
                down_77 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0f, -35f), Quaternion.identity);
                down_78 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0f, -35f), Quaternion.identity);
                down_79 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0f, -35f), Quaternion.identity);
                down_80 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0f, -35f), Quaternion.identity);
                down_81 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0f, -35f), Quaternion.identity);
                down_82 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0f, -35f), Quaternion.identity);
                down_83 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0f, -35f), Quaternion.identity);
                down_84 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0f, -35f), Quaternion.identity);
                down_85 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0f, -35f), Quaternion.identity);
                down_86 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0f, -35f), Quaternion.identity);
                down_87 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0f, -35f), Quaternion.identity);
                down_88 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0f, -35f), Quaternion.identity);
                down_89 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0f, -35f), Quaternion.identity);
                down_90 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0f, -35f), Quaternion.identity);
                down_91 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0f, -45f), Quaternion.identity);
                down_92 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0f, -45f), Quaternion.identity);
                down_93 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0f, -45f), Quaternion.identity);
                down_94 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0f, -45f), Quaternion.identity);
                down_95 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0f, -45f), Quaternion.identity);
                down_96 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0f, -45f), Quaternion.identity);
                down_97 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0f, -45f), Quaternion.identity);
                down_98 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0f, -45f), Quaternion.identity);
                down_99 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0f, -45f), Quaternion.identity);
                down_100 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0f, -45f), Quaternion.identity);
                down_101 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0f, -45f), Quaternion.identity);
                down_102 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0f, -45f), Quaternion.identity);
                down_103 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0f, -45f), Quaternion.identity);
                down_104 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0f, -45f), Quaternion.identity);
                down_105 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0f, -45f), Quaternion.identity);
                down_106 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0f, -55f), Quaternion.identity);
                down_107 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0f, -55f), Quaternion.identity);
                down_108 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0f, -55f), Quaternion.identity);
                down_109 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0f, -55f), Quaternion.identity);
                down_110 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0f, -55f), Quaternion.identity);
                down_111 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0f, -55f), Quaternion.identity);
                down_112 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0f, -55f), Quaternion.identity);
                down_113 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0f, -55f), Quaternion.identity);
                down_114 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0f, -55f), Quaternion.identity);
                down_115 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0f, -55f), Quaternion.identity);
                down_116 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0f, -55f), Quaternion.identity);
                down_117 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0f, -55f), Quaternion.identity);
                down_118 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0f, -55f), Quaternion.identity);
                down_119 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0f, -55f), Quaternion.identity);
                down_120 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0f, -55f), Quaternion.identity);
                down_121 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0f, -65f), Quaternion.identity);
                down_122 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0f, -65f), Quaternion.identity);
                down_123 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0f, -65f), Quaternion.identity);
                down_124 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0f, -65f), Quaternion.identity);
                down_125 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0f, -65f), Quaternion.identity);
                down_126 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0f, -65f), Quaternion.identity);
                down_127 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0f, -65f), Quaternion.identity);
                down_128 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0f, -65f), Quaternion.identity);
                down_129 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0f, -65f), Quaternion.identity);
                down_130 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0f, -65f), Quaternion.identity);
                down_131 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0f, -65f), Quaternion.identity);
                down_132 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0f, -65f), Quaternion.identity);
                down_133 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0f, -65f), Quaternion.identity);
                down_134 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0f, -65f), Quaternion.identity);
                down_135 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0f, -65f), Quaternion.identity);
                down_136 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0f, -75f), Quaternion.identity);
                down_137 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0f, -75f), Quaternion.identity);
                down_138 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0f, -75f), Quaternion.identity);
                down_139 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0f, -75f), Quaternion.identity);
                down_140 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0f, -75f), Quaternion.identity);
                down_141 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0f, -75f), Quaternion.identity);
                down_142 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0f, -75f), Quaternion.identity);
                down_143 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0f, -75f), Quaternion.identity);
                down_144 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0f, -75f), Quaternion.identity);
                down_145 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0f, -75f), Quaternion.identity);
                down_146 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0f, -75f), Quaternion.identity);
                down_147 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0f, -75f), Quaternion.identity);
                down_148 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0f, -75f), Quaternion.identity);
                down_149 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0f, -75f), Quaternion.identity);
                down_150 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0f, -75f), Quaternion.identity);
                down_151 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0f, -85f), Quaternion.identity);
                down_152 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0f, -85f), Quaternion.identity);
                down_153 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0f, -85f), Quaternion.identity);
                down_154 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0f, -85f), Quaternion.identity);
                down_155 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0f, -85f), Quaternion.identity);
                down_156 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0f, -85f), Quaternion.identity);
                down_157 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0f, -85f), Quaternion.identity);
                down_158 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0f, -85f), Quaternion.identity);
                down_159 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0f, -85f), Quaternion.identity);
                down_160 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0f, -85f), Quaternion.identity);
                down_161 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0f, -85f), Quaternion.identity);
                down_162 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0f, -85f), Quaternion.identity);
                down_163 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0f, -85f), Quaternion.identity);
                down_164 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0f, -85f), Quaternion.identity);
                down_165 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0f, -85f), Quaternion.identity);
                down_166 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0f, -95f), Quaternion.identity);
                down_167 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0f, -95f), Quaternion.identity);
                down_168 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0f, -95f), Quaternion.identity);
                down_169 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0f, -95f), Quaternion.identity);
                down_170 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0f, -95f), Quaternion.identity);
                down_171 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0f, -95f), Quaternion.identity);
                down_172 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0f, -95f), Quaternion.identity);
                down_173 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0f, -95f), Quaternion.identity);
                down_174 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0f, -95f), Quaternion.identity);
                down_175 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0f, -95f), Quaternion.identity);
                down_176 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0f, -95f), Quaternion.identity);
                down_177 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0f, -95f), Quaternion.identity);
                down_178 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0f, -95f), Quaternion.identity);
                down_179 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0f, -95f), Quaternion.identity);
                down_180 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0f, -95f), Quaternion.identity);
                down_181 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0f, -105f), Quaternion.identity);
                down_182 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0f, -105f), Quaternion.identity);
                down_183 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0f, -105f), Quaternion.identity);
                down_184 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0f, -105f), Quaternion.identity);
                down_185 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0f, -105f), Quaternion.identity);
                down_186 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0f, -105f), Quaternion.identity);
                down_187 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0f, -105f), Quaternion.identity);
                down_188 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0f, -105f), Quaternion.identity);
                down_189 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0f, -105f), Quaternion.identity);
                down_190 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0f, -105f), Quaternion.identity);
                down_191 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0f, -105f), Quaternion.identity);
                down_192 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0f, -105f), Quaternion.identity);
                down_193 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0f, -105f), Quaternion.identity);
                down_194 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0f, -105f), Quaternion.identity);
                down_195 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0f, -105f), Quaternion.identity);
                down_196 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0f, -115f), Quaternion.identity);
                down_197 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0f, -115f), Quaternion.identity);
                down_198 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0f, -115f), Quaternion.identity);
                down_199 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0f, -115f), Quaternion.identity);
                down_200 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0f, -115f), Quaternion.identity);
                down_201 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0f, -115f), Quaternion.identity);
                down_202 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0f, -115f), Quaternion.identity);
                down_203 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0f, -115f), Quaternion.identity);
                down_204 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0f, -115f), Quaternion.identity);
                down_205 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0f, -115f), Quaternion.identity);
                down_206 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0f, -115f), Quaternion.identity);
                down_207 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0f, -115f), Quaternion.identity);
                down_208 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0f, -115f), Quaternion.identity);
                down_209 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0f, -115f), Quaternion.identity);
                down_210 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0f, -115f), Quaternion.identity);
                down_211 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0f, -125f), Quaternion.identity);
                down_212 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0f, -125f), Quaternion.identity);
                down_213 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0f, -125f), Quaternion.identity);
                down_214 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0f, -125f), Quaternion.identity);
                down_215 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0f, -125f), Quaternion.identity);
                down_216 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0f, -125f), Quaternion.identity);
                down_217 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0f, -125f), Quaternion.identity);
                down_218 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0f, -125f), Quaternion.identity);
                down_219 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0f, -125f), Quaternion.identity);
                down_220 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0f, -125f), Quaternion.identity);
                down_221 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0f, -125f), Quaternion.identity);
                down_222 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0f, -125f), Quaternion.identity);
                down_223 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0f, -125f), Quaternion.identity);
                down_224 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0f, -125f), Quaternion.identity);
                down_225 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0f, -125f), Quaternion.identity);
            }
            bool light = true;
            if (light)
            {
                light_1 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0.1f, 15f), Quaternion.identity);
                light_2 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0.1f, 15f), Quaternion.identity);
                light_3 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0.1f, 15f), Quaternion.identity);
                light_4 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0.1f, 15f), Quaternion.identity);
                light_5 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0.1f, 15f), Quaternion.identity);
                light_6 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0.1f, 15f), Quaternion.identity);
                light_7 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0.1f, 15f), Quaternion.identity);
                light_8 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0.1f, 15f), Quaternion.identity);
                light_9 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0.1f, 15f), Quaternion.identity);
                light_10 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0.1f, 15f), Quaternion.identity);
                light_11 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0.1f, 15f), Quaternion.identity);
                light_12 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0.1f, 15f), Quaternion.identity);
                light_13 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0.1f, 15f), Quaternion.identity);
                light_14 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0.1f, 15f), Quaternion.identity);
                light_15 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0.1f, 15f), Quaternion.identity);
                light_16 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0.1f, 5f), Quaternion.identity);
                light_17 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0.1f, 5f), Quaternion.identity);
                light_18 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0.1f, 5f), Quaternion.identity);
                light_19 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0.1f, 5f), Quaternion.identity);
                light_20 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0.1f, 5f), Quaternion.identity);
                light_21 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0.1f, 5f), Quaternion.identity);
                light_22 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0.1f, 5f), Quaternion.identity);
                light_23 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0.1f, 5f), Quaternion.identity);
                light_24 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0.1f, 5f), Quaternion.identity);
                light_25 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0.1f, 5f), Quaternion.identity);
                light_26 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0.1f, 5f), Quaternion.identity);
                light_27 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0.1f, 5f), Quaternion.identity);
                light_28 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0.1f, 5f), Quaternion.identity);
                light_29 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0.1f, 5f), Quaternion.identity);
                light_30 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0.1f, 5f), Quaternion.identity);
                light_31 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0.1f, -5f), Quaternion.identity);
                light_32 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0.1f, -5f), Quaternion.identity);
                light_33 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0.1f, -5f), Quaternion.identity);
                light_34 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0.1f, -5f), Quaternion.identity);
                light_35 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0.1f, -5f), Quaternion.identity);
                light_36 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0.1f, -5f), Quaternion.identity);
                light_37 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0.1f, -5f), Quaternion.identity);
                light_38 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0.1f, -5f), Quaternion.identity);
                light_39 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0.1f, -5f), Quaternion.identity);
                light_40 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0.1f, -5f), Quaternion.identity);
                light_41 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0.1f, -5f), Quaternion.identity);
                light_42 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0.1f, -5f), Quaternion.identity);
                light_43 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0.1f, -5f), Quaternion.identity);
                light_44 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0.1f, -5f), Quaternion.identity);
                light_45 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0.1f, -5f), Quaternion.identity);
                light_46 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0.1f, -15f), Quaternion.identity);
                light_47 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0.1f, -15f), Quaternion.identity);
                light_48 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0.1f, -15f), Quaternion.identity);
                light_49 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0.1f, -15f), Quaternion.identity);
                light_50 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0.1f, -15f), Quaternion.identity);
                light_51 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0.1f, -15f), Quaternion.identity);
                light_52 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0.1f, -15f), Quaternion.identity);
                light_53 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0.1f, -15f), Quaternion.identity);
                light_54 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0.1f, -15f), Quaternion.identity);
                light_55 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0.1f, -15f), Quaternion.identity);
                light_56 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0.1f, -15f), Quaternion.identity);
                light_57 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0.1f, -15f), Quaternion.identity);
                light_58 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0.1f, -15f), Quaternion.identity);
                light_59 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0.1f, -15f), Quaternion.identity);
                light_60 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0.1f, -15f), Quaternion.identity);
                light_61 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0.1f, -25f), Quaternion.identity);
                light_62 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0.1f, -25f), Quaternion.identity);
                light_63 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0.1f, -25f), Quaternion.identity);
                light_64 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0.1f, -25f), Quaternion.identity);
                light_65 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0.1f, -25f), Quaternion.identity);
                light_66 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0.1f, -25f), Quaternion.identity);
                light_67 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0.1f, -25f), Quaternion.identity);
                light_68 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0.1f, -25f), Quaternion.identity);
                light_69 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0.1f, -25f), Quaternion.identity);
                light_70 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0.1f, -25f), Quaternion.identity);
                light_71 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0.1f, -25f), Quaternion.identity);
                light_72 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0.1f, -25f), Quaternion.identity);
                light_73 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0.1f, -25f), Quaternion.identity);
                light_74 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0.1f, -25f), Quaternion.identity);
                light_75 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0.1f, -25f), Quaternion.identity);
                light_76 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0.1f, -35f), Quaternion.identity);
                light_77 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0.1f, -35f), Quaternion.identity);
                light_78 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0.1f, -35f), Quaternion.identity);
                light_79 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0.1f, -35f), Quaternion.identity);
                light_80 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0.1f, -35f), Quaternion.identity);
                light_81 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0.1f, -35f), Quaternion.identity);
                light_82 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0.1f, -35f), Quaternion.identity);
                light_83 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0.1f, -35f), Quaternion.identity);
                light_84 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0.1f, -35f), Quaternion.identity);
                light_85 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0.1f, -35f), Quaternion.identity);
                light_86 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0.1f, -35f), Quaternion.identity);
                light_87 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0.1f, -35f), Quaternion.identity);
                light_88 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0.1f, -35f), Quaternion.identity);
                light_89 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0.1f, -35f), Quaternion.identity);
                light_90 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0.1f, -35f), Quaternion.identity);
                light_91 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0.1f, -45f), Quaternion.identity);
                light_92 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0.1f, -45f), Quaternion.identity);
                light_93 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0.1f, -45f), Quaternion.identity);
                light_94 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0.1f, -45f), Quaternion.identity);
                light_95 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0.1f, -45f), Quaternion.identity);
                light_96 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0.1f, -45f), Quaternion.identity);
                light_97 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0.1f, -45f), Quaternion.identity);
                light_98 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0.1f, -45f), Quaternion.identity);
                light_99 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0.1f, -45f), Quaternion.identity);
                light_100 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0.1f, -45f), Quaternion.identity);
                light_101 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0.1f, -45f), Quaternion.identity);
                light_102 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0.1f, -45f), Quaternion.identity);
                light_103 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0.1f, -45f), Quaternion.identity);
                light_104 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0.1f, -45f), Quaternion.identity);
                light_105 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0.1f, -45f), Quaternion.identity);
                light_106 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0.1f, -55f), Quaternion.identity);
                light_107 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0.1f, -55f), Quaternion.identity);
                light_108 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0.1f, -55f), Quaternion.identity);
                light_109 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0.1f, -55f), Quaternion.identity);
                light_110 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0.1f, -55f), Quaternion.identity);
                light_111 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0.1f, -55f), Quaternion.identity);
                light_112 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0.1f, -55f), Quaternion.identity);
                light_113 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0.1f, -55f), Quaternion.identity);
                light_114 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0.1f, -55f), Quaternion.identity);
                light_115 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0.1f, -55f), Quaternion.identity);
                light_116 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0.1f, -55f), Quaternion.identity);
                light_117 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0.1f, -55f), Quaternion.identity);
                light_118 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0.1f, -55f), Quaternion.identity);
                light_119 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0.1f, -55f), Quaternion.identity);
                light_120 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0.1f, -55f), Quaternion.identity);
                light_121 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0.1f, -65f), Quaternion.identity);
                light_122 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0.1f, -65f), Quaternion.identity);
                light_123 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0.1f, -65f), Quaternion.identity);
                light_124 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0.1f, -65f), Quaternion.identity);
                light_125 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0.1f, -65f), Quaternion.identity);
                light_126 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0.1f, -65f), Quaternion.identity);
                light_127 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0.1f, -65f), Quaternion.identity);
                light_128 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0.1f, -65f), Quaternion.identity);
                light_129 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0.1f, -65f), Quaternion.identity);
                light_130 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0.1f, -65f), Quaternion.identity);
                light_131 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0.1f, -65f), Quaternion.identity);
                light_132 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0.1f, -65f), Quaternion.identity);
                light_133 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0.1f, -65f), Quaternion.identity);
                light_134 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0.1f, -65f), Quaternion.identity);
                light_135 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0.1f, -65f), Quaternion.identity);
                light_136 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0.1f, -75f), Quaternion.identity);
                light_137 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0.1f, -75f), Quaternion.identity);
                light_138 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0.1f, -75f), Quaternion.identity);
                light_139 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0.1f, -75f), Quaternion.identity);
                light_140 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0.1f, -75f), Quaternion.identity);
                light_141 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0.1f, -75f), Quaternion.identity);
                light_142 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0.1f, -75f), Quaternion.identity);
                light_143 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0.1f, -75f), Quaternion.identity);
                light_144 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0.1f, -75f), Quaternion.identity);
                light_145 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0.1f, -75f), Quaternion.identity);
                light_146 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0.1f, -75f), Quaternion.identity);
                light_147 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0.1f, -75f), Quaternion.identity);
                light_148 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0.1f, -75f), Quaternion.identity);
                light_149 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0.1f, -75f), Quaternion.identity);
                light_150 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0.1f, -75f), Quaternion.identity);
                light_151 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0.1f, -85f), Quaternion.identity);
                light_152 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0.1f, -85f), Quaternion.identity);
                light_153 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0.1f, -85f), Quaternion.identity);
                light_154 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0.1f, -85f), Quaternion.identity);
                light_155 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0.1f, -85f), Quaternion.identity);
                light_156 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0.1f, -85f), Quaternion.identity);
                light_157 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0.1f, -85f), Quaternion.identity);
                light_158 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0.1f, -85f), Quaternion.identity);
                light_159 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0.1f, -85f), Quaternion.identity);
                light_160 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0.1f, -85f), Quaternion.identity);
                light_161 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0.1f, -85f), Quaternion.identity);
                light_162 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0.1f, -85f), Quaternion.identity);
                light_163 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0.1f, -85f), Quaternion.identity);
                light_164 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0.1f, -85f), Quaternion.identity);
                light_165 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0.1f, -85f), Quaternion.identity);
                light_166 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0.1f, -95f), Quaternion.identity);
                light_167 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0.1f, -95f), Quaternion.identity);
                light_168 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0.1f, -95f), Quaternion.identity);
                light_169 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0.1f, -95f), Quaternion.identity);
                light_170 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0.1f, -95f), Quaternion.identity);
                light_171 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0.1f, -95f), Quaternion.identity);
                light_172 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0.1f, -95f), Quaternion.identity);
                light_173 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0.1f, -95f), Quaternion.identity);
                light_174 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0.1f, -95f), Quaternion.identity);
                light_175 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0.1f, -95f), Quaternion.identity);
                light_176 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0.1f, -95f), Quaternion.identity);
                light_177 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0.1f, -95f), Quaternion.identity);
                light_178 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0.1f, -95f), Quaternion.identity);
                light_179 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0.1f, -95f), Quaternion.identity);
                light_180 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0.1f, -95f), Quaternion.identity);
                light_181 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0.1f, -105f), Quaternion.identity);
                light_182 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0.1f, -105f), Quaternion.identity);
                light_183 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0.1f, -105f), Quaternion.identity);
                light_184 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0.1f, -105f), Quaternion.identity);
                light_185 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0.1f, -105f), Quaternion.identity);
                light_186 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0.1f, -105f), Quaternion.identity);
                light_187 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0.1f, -105f), Quaternion.identity);
                light_188 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0.1f, -105f), Quaternion.identity);
                light_189 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0.1f, -105f), Quaternion.identity);
                light_190 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0.1f, -105f), Quaternion.identity);
                light_191 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0.1f, -105f), Quaternion.identity);
                light_192 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0.1f, -105f), Quaternion.identity);
                light_193 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0.1f, -105f), Quaternion.identity);
                light_194 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0.1f, -105f), Quaternion.identity);
                light_195 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0.1f, -105f), Quaternion.identity);
                light_196 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0.1f, -115f), Quaternion.identity);
                light_197 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0.1f, -115f), Quaternion.identity);
                light_198 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0.1f, -115f), Quaternion.identity);
                light_199 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0.1f, -115f), Quaternion.identity);
                light_200 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0.1f, -115f), Quaternion.identity);
                light_201 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0.1f, -115f), Quaternion.identity);
                light_202 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0.1f, -115f), Quaternion.identity);
                light_203 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0.1f, -115f), Quaternion.identity);
                light_204 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0.1f, -115f), Quaternion.identity);
                light_205 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0.1f, -115f), Quaternion.identity);
                light_206 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0.1f, -115f), Quaternion.identity);
                light_207 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0.1f, -115f), Quaternion.identity);
                light_208 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0.1f, -115f), Quaternion.identity);
                light_209 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0.1f, -115f), Quaternion.identity);
                light_210 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0.1f, -115f), Quaternion.identity);
                light_211 = PhotonNetwork.Instantiate(down_p.name, new Vector3(-5f, 0.1f, -125f), Quaternion.identity);
                light_212 = PhotonNetwork.Instantiate(down_p.name, new Vector3(5f, 0.1f, -125f), Quaternion.identity);
                light_213 = PhotonNetwork.Instantiate(down_p.name, new Vector3(15f, 0.1f, -125f), Quaternion.identity);
                light_214 = PhotonNetwork.Instantiate(down_p.name, new Vector3(25f, 0.1f, -125f), Quaternion.identity);
                light_215 = PhotonNetwork.Instantiate(down_p.name, new Vector3(35f, 0.1f, -125f), Quaternion.identity);
                light_216 = PhotonNetwork.Instantiate(down_p.name, new Vector3(45f, 0.1f, -125f), Quaternion.identity);
                light_217 = PhotonNetwork.Instantiate(down_p.name, new Vector3(55f, 0.1f, -125f), Quaternion.identity);
                light_218 = PhotonNetwork.Instantiate(down_p.name, new Vector3(65f, 0.1f, -125f), Quaternion.identity);
                light_219 = PhotonNetwork.Instantiate(down_p.name, new Vector3(75f, 0.1f, -125f), Quaternion.identity);
                light_220 = PhotonNetwork.Instantiate(down_p.name, new Vector3(85f, 0.1f, -125f), Quaternion.identity);
                light_221 = PhotonNetwork.Instantiate(down_p.name, new Vector3(95f, 0.1f, -125f), Quaternion.identity);
                light_222 = PhotonNetwork.Instantiate(down_p.name, new Vector3(105f, 0.1f, -125f), Quaternion.identity);
                light_223 = PhotonNetwork.Instantiate(down_p.name, new Vector3(115f, 0.1f, -125f), Quaternion.identity);
                light_224 = PhotonNetwork.Instantiate(down_p.name, new Vector3(125f, 0.1f, -125f), Quaternion.identity);
                light_225 = PhotonNetwork.Instantiate(down_p.name, new Vector3(135f, 0.1f, -125f), Quaternion.identity);

            }
            pir_w_1 = PhotonNetwork.Instantiate(pir_w.name, new Vector3(+5f, 0f, -58.3f), Quaternion.identity);
            pir_w_2 = PhotonNetwork.Instantiate(pir_w.name, new Vector3(+5f, 0f, -56.2f), Quaternion.identity);
            pir_w_3 = PhotonNetwork.Instantiate(pir_w.name, new Vector3(+5f, 0f, -54.1f), Quaternion.identity);
            boat_w_1 = PhotonNetwork.Instantiate(boat_w.name, new Vector3(+5f, 0.3f, -55f), Quaternion.Euler(90f, -90f, 0f)); 

            Debug.Log("Pir and boat created (Player1)");
            FO.ToT();
            down_1.GetComponent<Renderer>().material = mat;
        }
        if (PhotonNetwork.CurrentRoom.PlayerCount == 2)
        {
            pir_b_1 = PhotonNetwork.Instantiate(pir_b.name, new Vector3(+125f, 0f, -55.9f), Quaternion.identity);
            pir_b_2 = PhotonNetwork.Instantiate(pir_b.name, new Vector3(+125f, 0f, -53.8f), Quaternion.identity);
            pir_b_3 = PhotonNetwork.Instantiate(pir_b.name, new Vector3(+125f, 0f, -51.7f), Quaternion.identity);
            boat_b_1 = PhotonNetwork.Instantiate(boat_b.name, new Vector3(+125f, 0.3f, -55f), Quaternion.Euler(90f, 90f, 0f));
           // pir_w_1 = Player1.pir_w_1;//PhotonNetwork.Instantiate(pir_w.name, new Vector3(+5f, 0f, -58.3f), Quaternion.identity);
           // pir_w_2 = ;//PhotonNetwork.Instantiate(pir_w.name, new Vector3(+5f, 0f, -56.2f), Quaternion.identity);
           // pir_w_3 = ;//PhotonNetwork.Instantiate(pir_w.name, new Vector3(+5f, 0f, -54.1f), Quaternion.identity);
           // boat_w_1 = ;//PhotonNetwork.Instantiate(boat_w.name, new Vector3(+5f, 0.3f, -55f), Quaternion.Euler(90f, -90f, 0f));
            Debug.Log("Pir and boat created (Player2)");
        }
        /* Obj93.transform.position = new Vector3(+5f, 0.3f, -55f);
            Obj97.transform.position = new Vector3(+125f, 0.3f, -55f);
            Obj101.transform.position = new Vector3(+65f, 0.3f, 5f);
            Obj105.transform.position = new Vector3(+65f, 0.3f, -115f);
            Obj90.transform.position = new Vector3(+5f, 0f, -58.3f);
            Obj91.transform.position = new Vector3(+5f, 0f, -56.2f);
            Obj92.transform.position = new Vector3(+5f, 0f, -54.1f);
           // Obj94.transform.position = new Vector3(+125f, 0f, -55.9f);
           // Obj95.transform.position = new Vector3(+125f, 0f, -53.8f);
            //Obj96.transform.position = new Vector3(+125f, 0f, -51.7f);
            Obj98.transform.position = new Vector3(+65f - 3.3f, 0, 5f);
            Obj99.transform.position = new Vector3(+65f - 1.2f, 0, 5f);
            Obj100.transform.position = new Vector3(+65f + 0.9f, 0, 5f);
            Obj102.transform.position = new Vector3(+65f + 3.3f, 0, -115f);
            Obj103.transform.position = new Vector3(+65f + 1.2f, 0, -115f);
            Obj104.transform.position = new Vector3(+65f - 0.9f, 0, -115f);*//*
        if (PhotonNetwork.CurrentRoom.PlayerCount == 3)
        {
            pir_y_1 = PhotonNetwork.Instantiate(pir_y.name, new Vector3(+65f - 3.3f, 0f, 5f), Quaternion.identity);
            pir_y_2 = PhotonNetwork.Instantiate(pir_y.name, new Vector3(+65f - 1.2f, 0f, 5f), Quaternion.identity);
            pir_y_3 = PhotonNetwork.Instantiate(pir_y.name, new Vector3(+65f + 0.9f, 0f, 5f), Quaternion.identity);
            boat_y_1 = PhotonNetwork.Instantiate(boat_y.name, new Vector3(+65f, 0.3f, 5f), Quaternion.Euler(90f, 0f, 0f));
            // pir_w_1 = Player1.pir_w_1;//PhotonNetwork.Instantiate(pir_w.name, new Vector3(+5f, 0f, -58.3f), Quaternion.identity);
            // pir_w_2 = ;//PhotonNetwork.Instantiate(pir_w.name, new Vector3(+5f, 0f, -56.2f), Quaternion.identity);
            // pir_w_3 = ;//PhotonNetwork.Instantiate(pir_w.name, new Vector3(+5f, 0f, -54.1f), Quaternion.identity);
            // boat_w_1 = ;//PhotonNetwork.Instantiate(boat_w.name, new Vector3(+5f, 0.3f, -55f), Quaternion.Euler(90f, -90f, 0f));
            Debug.Log("Pir and boat created (Player2)");
        }
        if (PhotonNetwork.CurrentRoom.PlayerCount == 4)
        {
            pir_r_1 = PhotonNetwork.Instantiate(pir_r.name, new Vector3(+65f + 0.9f, 0f, -115f), Quaternion.identity);
            pir_r_2 = PhotonNetwork.Instantiate(pir_r.name, new Vector3(+65f + 1.2f, 0f, -115f), Quaternion.identity);
            pir_r_3 = PhotonNetwork.Instantiate(pir_r.name, new Vector3(+65f - 0.9f, 0f, -115f), Quaternion.identity);
            boat_r_1 = PhotonNetwork.Instantiate(boat_r.name, new Vector3(+65f, 0.3f, -115f), Quaternion.Euler(90f, 180f, 0f));
            // pir_w_1 = Player1.pir_w_1;//PhotonNetwork.Instantiate(pir_w.name, new Vector3(+5f, 0f, -58.3f), Quaternion.identity);
            // pir_w_2 = ;//PhotonNetwork.Instantiate(pir_w.name, new Vector3(+5f, 0f, -56.2f), Quaternion.identity);
            // pir_w_3 = ;//PhotonNetwork.Instantiate(pir_w.name, new Vector3(+5f, 0f, -54.1f), Quaternion.identity);
            // boat_w_1 = ;//PhotonNetwork.Instantiate(boat_w.name, new Vector3(+5f, 0.3f, -55f), Quaternion.Euler(90f, -90f, 0f));
            Debug.Log("Pir and boat created (Player2)");
        }*/
    }
    public void LeaveRoom()// покидаем комнату
    {
        PhotonNetwork.LeaveRoom();
        Debug.Log("LeaveRoom");
    }
    public override void OnLeftRoom()//наш игрок ливнул в лобби
    {
        SceneManager.LoadScene(0);
        Debug.Log("OnLeftRoom");
    }
    public override void OnPlayerEnteredRoom(Player newPlayer)// игрок присоединился
    {
        Debug.Log("Other player entred room - " + newPlayer.NickName);
    }
    public override void OnPlayerLeftRoom(Player otherPlayer)// игрок ливнул
    {
        Debug.Log("Other player left room - " + otherPlayer.NickName);
    }
    private void Update()
    {
        if ((Exit))
        {
            LeaveRoom();
            Exit = false;
        }
    }

}
